bin = [
    { name = "day1", path = "day1/main.rs" },
    { name = "day2", path = "day2/main.rs" },
    { name = "day3", path = "day3/main.rs" },
    { name = "day4", path = "day4/main.rs" },
]

[package]
name = "advent_of_code_2024"
edition = "2021"

[dependencies]
regex = "1.11.1"
